from .gat import GAT
from .gcn import GCN
from .median import MedianGCN
from .trimmed_gcn import TrimmedGCN
from .fastgcn import FastGCN
from .dagnn import DAGNN
from .parinorm import *
from .simpgcn import SimPGCN
from .mlp import MLP
from .tagcn import TAGCN
from .appnp import APPNP
from .label_propagation import LabelPropagation
